#!/usr/bin/env node
// Extracts the marked section of the gsheets-pro SKILL.md into two artifacts:
//
//   CARD.md          the ~1,200-token brief the session-start and first-call
//                    hooks inject, so an agent that never loads the skill still
//                    gets the loop, the ten rules, and the refusal semantics.
//   CARD.digest.txt  a hard-capped digest for the MCP server's `instructions`
//                    field, which tops out at 2 KB.
//
// Both are generated. Edit the marked section of SKILL.md, never these files.
//
//   node scripts/card.mjs          write both, fail over budget
//   node scripts/card.mjs --check  verify the committed files are current
//
// Run in CI. A card over budget is a real regression: it is injected into every
// session that touches a spreadsheet.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const SKILL_DIR = join(ROOT, "plugins/gsheets-pro/skills/gsheets-pro");

const SKILL_PATH = join(SKILL_DIR, "SKILL.md");
const CARD_PATH = join(SKILL_DIR, "CARD.md");
const DIGEST_PATH = join(SKILL_DIR, "CARD.digest.txt");

const BEGIN = "<!-- CARD:BEGIN -->";
const END = "<!-- CARD:END -->";

// Budgets. The card is a token budget because it is injected into a context
// window. The digest is a byte budget because the MCP `instructions` field is
// capped in bytes, and we leave headroom under 2 KB for the framing the server
// adds around it.
const CARD_TOKEN_BUDGET = 1400;
const DIGEST_BYTE_BUDGET = 1900;

// Rough and deliberately so. Real tokenization needs a tokenizer dependency
// this repo does not want, and four characters per token runs slightly
// pessimistic on English prose, which is the safe direction for a budget.
const estimateTokens = (text) => Math.ceil(text.length / 4);

const GENERATED_NOTE =
  "<!-- Generated by scripts/card.mjs from the marked section of SKILL.md. Do not edit. -->";

function extractCard(skill) {
  const start = skill.indexOf(BEGIN);
  const end = skill.indexOf(END);

  if (start === -1 || end === -1) {
    fail(
      `SKILL.md is missing its card markers.\n` +
        `Wrap the section that should become the card in ${BEGIN} and ${END}.`,
    );
  }
  if (end < start) {
    fail(`SKILL.md has ${END} before ${BEGIN}.`);
  }

  const body = skill.slice(start + BEGIN.length, end).trim();
  if (!body) {
    fail("The marked card section in SKILL.md is empty.");
  }
  return body;
}

// The digest is the card with everything a 1,900-byte field cannot afford
// removed: the prose paragraphs, the tables, and the explanatory second halves.
// What survives is each heading as a bare label, plus every list item reduced
// to its imperative.
//
// The card is written so that reduction is lossless where it matters: each rule
// opens with a bold span that is the whole instruction, and the sentences after
// it are the reasoning. So the digest prefers the bold span, and falls back to
// the first sentence for items that have none.
function buildDigest(card) {
  const items = [];

  for (const raw of card.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("|")) continue;
    if (/^[-|: ]+$/.test(line)) continue;

    const heading = /^#{1,6}\s+(.*)$/.exec(line);
    if (heading) {
      items.push({ kind: "heading", text: heading[1] });
      continue;
    }
    const numbered = /^(\d+)\.\s+(.*)$/.exec(line);
    if (numbered) {
      items.push({ kind: "item", marker: `${numbered[1]}.`, text: numbered[2] });
      continue;
    }
    const bulleted = /^[-*]\s+(.*)$/.exec(line);
    if (bulleted) {
      items.push({ kind: "item", marker: "-", text: bulleted[1] });
      continue;
    }
    // A wrapped continuation of the list item above.
    const last = items[items.length - 1];
    if (last && last.kind === "item") last.text += ` ${line}`;
  }

  const clean = (text) =>
    text
      .replace(/`/g, "")
      .replace(/\s+/g, " ")
      .trim();

  const imperative = (text) => {
    const bold = /^\*\*(.+?)\*\*(.*)$/s.exec(text.trim());
    if (bold) {
      const lead = clean(bold[1]);
      // "Build in this order:" is a stem, not an instruction. Carry the clause
      // that completes it.
      if (lead.endsWith(":")) {
        const rest = clean(bold[2]);
        const sentence = /^(.+?[.!?])(\s|$)/.exec(rest);
        return `${lead} ${sentence ? sentence[1] : rest}`.trim();
      }
      return lead;
    }
    const stripped = clean(text.replace(/\*\*/g, ""));
    const sentence = /^(.+?[.!?])(\s|$)/.exec(stripped);
    return sentence ? sentence[1] : stripped;
  };

  const header =
    "gsheets-pro house rules. The full guide is the gsheets-pro skill; " +
    "invoke it for a build, a restyle, or work in a spreadsheet other people edit.";

  const render = (list) => {
    const out = [header];
    for (const item of list) {
      if (item.kind === "heading") out.push("", `${clean(item.text).toUpperCase()}`);
      else out.push(`${item.marker} ${imperative(item.text)}`);
    }
    return out.join("\n");
  };

  let kept = items.slice();
  let digest = render(kept);

  // If it still overruns, drop from the end rather than truncating mid
  // sentence, and say that it was cut.
  while (Buffer.byteLength(digest, "utf8") > DIGEST_BYTE_BUDGET && kept.length > 0) {
    kept.pop();
    digest = `${render(kept)}\n\nTruncated. The skill carries the rest.`;
  }

  return digest;
}

function fail(message) {
  process.stderr.write(`card.mjs: ${message}\n`);
  process.exit(1);
}

function main() {
  const checkOnly = process.argv.includes("--check");

  const skill = readFileSync(SKILL_PATH, "utf8");
  const card = extractCard(skill);
  const digest = buildDigest(card);

  const cardFile = `${GENERATED_NOTE}\n\n${card}\n`;
  const digestFile = `${digest}\n`;

  const tokens = estimateTokens(card);
  const digestBytes = Buffer.byteLength(digest, "utf8");

  const rel = (p) => relative(ROOT, p);

  process.stdout.write(
    `card:   ${tokens} tokens (budget ${CARD_TOKEN_BUDGET}), ${card.length} chars -> ${rel(CARD_PATH)}\n` +
      `digest: ${digestBytes} bytes (budget ${DIGEST_BYTE_BUDGET}) -> ${rel(DIGEST_PATH)}\n`,
  );

  if (tokens > CARD_TOKEN_BUDGET) {
    fail(
      `the card is ${tokens} tokens, over the ${CARD_TOKEN_BUDGET} budget by ${tokens - CARD_TOKEN_BUDGET}.\n` +
        `Cut the marked section of SKILL.md. Move what you cut into a reference file; ` +
        `the card is injected into every session that touches a spreadsheet.`,
    );
  }
  if (digestBytes > DIGEST_BYTE_BUDGET) {
    fail(`the digest is ${digestBytes} bytes, over the ${DIGEST_BYTE_BUDGET} budget.`);
  }

  if (checkOnly) {
    const stale = [];
    for (const [path, want] of [
      [CARD_PATH, cardFile],
      [DIGEST_PATH, digestFile],
    ]) {
      let have = null;
      try {
        have = readFileSync(path, "utf8");
      } catch {
        stale.push(`${rel(path)} is missing`);
        continue;
      }
      if (have !== want) stale.push(`${rel(path)} is out of date`);
    }
    if (stale.length > 0) {
      fail(`${stale.join("; ")}. Run: node scripts/card.mjs`);
    }
    process.stdout.write("card and digest are current.\n");
    return;
  }

  writeFileSync(CARD_PATH, cardFile, "utf8");
  writeFileSync(DIGEST_PATH, digestFile, "utf8");
}

main();
